sudo: true
dist: xenial
language: python
cache:
  pip: true
  directories:
  - "$TRAVIS_BUILD_DIR/.tox"
python:
- 2.7
- 3.7
before_script:
- flake8 --verbose --jobs=8
script:
- python setup.py test
deploy:
  provider: pypi
  user: ohyanagi
  password:
    secure: uMB6+5SrppN3PBrwdt5LBnH7tj7Ve631xTZJd7byaX7Tj82aj8ha2f7lOG/awj8uKfBh0dPSflvsW/IEMUBmOTicmNa7KPb5fomnA0LjG6XOORtRpwzHaezcPTfke9cMROObB4xa5JCsFyLRuZFNFYdpQNWBQ1+ocj7KrgAweyaWuXCxhtw1ISt8k69jYZ+nLc0tLbBqWtf8/T8C1ZgMnjPHBAXIZaN3nOV4Uxn6My4zEZfBBAaDiLsA4J3yHZSx2X24IrxPvdGCpV7oqzazl0YXMb2Ls6yipR5r1YmHR6fHFRPTon0j3ioqYQ5HzwrLqsxfHLNiESnmUxFGjrxMHQ9/RgCND3Ow6UIKJBTj0kFJ3Q++Xxu2Orw/tqDT7ToRLuqlTAe5JlDgbd8LD3VEi/3Ld/OgoIe7cD/XjyiluOPkxW8Rw7C9Fars97CmskeSOCIViFwRdIuft8+L7zkBO1pDetlGsgJTk2zZMJufuTzVKXIPXOQglBMJFQwwhHc2OAKWpWJQu9F7XdPcscqlE1DHsRXZ5+K4V2AQPutngqNr36RCeSG3fW7qXTmLYA/Uwqn1msOlc2S1DNeUOFy8x1GcwLilFNUYo+3wRNQcfbCTXffl0t5axE4bI0uegGzNNMHtR9RdgS7GfmBZ3XtLmAqAjiQe67w2N527RU2HFXY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: heavenshell/py-pixela
    python: 3.7
